# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5nB6hbbdapzkW3VsuqBG3fe9BZ8TK5K
"""

# ------------------------------------------------------------
# 🇲🇷 Visualisations Macroéconomiques – Mauritanie
# Données réelles | Palette bleue | Nettoyage intelligent | Export haute résolution
# ------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# -----------------------------
# 1. CHARGEMENT ET NETTOYAGE DES DONNÉES
# -----------------------------
uploaded = files.upload()  # Téléverse ton fichier CSV
df = pd.read_csv("macro_mauritanie_complet_1960_2024.csv")

# S'assurer que l'année est entière
df["Année"] = df["Année"].astype(int)

# Fusionner les doublons par année (garder la première valeur non-nulle)
df = df.groupby("Année", as_index=False).first()
df = df.sort_values("Année").reset_index(drop=True)

print("✅ Période couverte :", df["Année"].min(), "–", df["Année"].max())

# -----------------------------
# 2. IMPUTATION INTELLIGENTE PAR VARIABLE
# -----------------------------

# Croissance PIB (>=1962)
mask = df["Année"] >= 1962
df.loc[mask, "Croissance_PIB_pct"] = df.loc[mask, "Croissance_PIB_pct"].interpolate()

# Inflation (>=1986)
mask = df["Année"] >= 1986
df.loc[mask, "Inflation_pct"] = df.loc[mask, "Inflation_pct"].interpolate()

# Recettes fiscales % PIB (2007–2024)
mask = (df["Année"] >= 2007) & (df["Année"] <= 2024)
df.loc[mask, "Recettes_fiscales_pct_PIB"] = df.loc[mask, "Recettes_fiscales_pct_PIB"].interpolate()

# Envois de fonds (>=1975) → interpolation limitée + moyenne
mask = df["Année"] >= 1975
df.loc[mask, "Envois_de_fonds_pct_PIB"] = (
    df.loc[mask, "Envois_de_fonds_pct_PIB"]
    .interpolate(limit=4)
    .fillna(df.loc[mask, "Envois_de_fonds_pct_PIB"].mean())
)

# Dette extérieure (>=1970)
mask = df["Année"] >= 1970
df.loc[mask, "Dette_exterieure_USD"] = df.loc[mask, "Dette_exterieure_USD"].interpolate()

# Solde commercial (>=1961) → moyenne
mask = df["Année"] >= 1961
df.loc[mask, "Solde_commercial_pct_PIB"] = df.loc[mask, "Solde_commercial_pct_PIB"].fillna(
    df.loc[mask, "Solde_commercial_pct_PIB"].mean()
)

# Réserves (1963–2021)
mask = (df["Année"] >= 1963) & (df["Année"] <= 2021)
df.loc[mask, "Reserves_internationales_USD"] = df.loc[mask, "Reserves_internationales_USD"].interpolate()

# Recettes absolues (2007–2021)
mask = (df["Année"] >= 2007) & (df["Année"] <= 2021)
df.loc[mask, "Recettes_millions_MR"] = df.loc[mask, "Recettes_millions_MR"].interpolate()

# Taux de chômage (2007–2021) → moyenne
mask = (df["Année"] >= 2007) & (df["Année"] <= 2021)
df.loc[mask, "Taux_chomage_pct"] = df.loc[mask, "Taux_chomage_pct"].fillna(
    df.loc[mask, "Taux_chomage_pct"].mean()
)

# Taux d’intérêt (2007–2017) → fixer à 17%
mask = (df["Année"] >= 2007) & (df["Année"] <= 2017)
df.loc[mask, "Taux_interet_pct"] = df.loc[mask, "Taux_interet_pct"].fillna(17.0)

# -----------------------------
# 3. CONFIGURATION VISUELLE
# -----------------------------
BLEU_FONCE = "#0B3C5D"
BLEU_MOYEN = "#1F77B4"
BLEU_CLAIR = "#AEC7E8"
BLEU_TRES_CLAIR = "#E6F0FA"

plt.rcParams.update({
    "axes.edgecolor": BLEU_FONCE,
    "axes.labelcolor": BLEU_FONCE,
    "xtick.color": BLEU_FONCE,
    "ytick.color": BLEU_FONCE,
    "text.color": BLEU_FONCE,
    "font.size": 11,
    "figure.dpi": 300
})

# -----------------------------
# 4. VISUALISATIONS AMÉLIORÉES
# -----------------------------

def save_fig(name):
    plt.savefig(f"{name}.png", dpi=300, bbox_inches="tight")

# 1. Croissance du PIB avec cycles
plt.figure(figsize=(14, 4))
plt.plot(df["Année"], df["Croissance_PIB_pct"], color=BLEU_FONCE, linewidth=2, label="Croissance")
plt.plot(df["Année"], df["Croissance_PIB_pct"].rolling(10).mean(), color=BLEU_MOYEN, linewidth=3, label="Tendance long terme")
plt.fill_between(df["Année"], df["Croissance_PIB_pct"], where=df["Croissance_PIB_pct"] < 0, color=BLEU_CLAIR, alpha=0.6)
for year, label in zip([1975, 2009, 2020], ["Choc pétrolier", "Crise financière", "COVID-19"]):
    if year in df["Année"].values:
        y = df.loc[df["Année"] == year, "Croissance_PIB_pct"].values[0]
        plt.annotate(label, xy=(year, y), xytext=(year, y-6),
                     arrowprops=dict(arrowstyle="->", color=BLEU_FONCE), ha="center", fontsize=9)
plt.axhline(0, linestyle="--", color="gray")
plt.title("Croissance du PIB – cycles économiques et chocs\nSource : BCM, FMI, Banque Mondiale", weight="bold")
plt.ylabel("%")
plt.legend()
plt.grid(axis="y", alpha=0.3)
save_fig("1_croissance_pib_cycles")
plt.show()

# 2. Inflation – régimes
plt.figure(figsize=(14, 4))
median = df["Inflation_pct"].median()
plt.plot(df["Année"], df["Inflation_pct"], color=BLEU_FONCE, linewidth=2)
plt.axhline(median, linestyle="--", color=BLEU_MOYEN, label=f"Inflation médiane ({median:.1f}%)")
plt.fill_between(df["Année"], median, df["Inflation_pct"], where=df["Inflation_pct"] > median, color=BLEU_CLAIR, alpha=0.6, label="Régime inflation élevée")
plt.title("Inflation – régimes macroéconomiques\nSource : BCM, FMI", weight="bold")
plt.ylabel("%")
plt.legend()
plt.grid(axis="y", alpha=0.3)
save_fig("2_inflation_regimes")
plt.show()

# 3. Dette vs Réserves
plt.figure(figsize=(14, 5))
plt.plot(df["Année"], df["Dette_exterieure_USD"]/1e9, color=BLEU_FONCE, linewidth=2, label="Dette extérieure")
plt.plot(df["Année"], df["Reserves_internationales_USD"]/1e9, color=BLEU_MOYEN, linewidth=2, label="Réserves")
plt.fill_between(df["Année"], df["Reserves_internationales_USD"]/1e9, df["Dette_exterieure_USD"]/1e9,
                 where=df["Dette_exterieure_USD"] > df["Reserves_internationales_USD"],
                 color=BLEU_CLAIR, alpha=0.6, label="Zone de vulnérabilité externe")
plt.title("Soutenabilité externe : dette vs réserves\nSource : Banque Mondiale", weight="bold")
plt.ylabel("Milliards USD")
plt.legend()
plt.grid(axis="y", alpha=0.3)
save_fig("3_dette_reserves")
plt.show()